name: Update GitHub Stars

on:
  schedule:
    - cron: '0 1 * * *'  # Run the script daily at 1:00 AM UTC

jobs:
  update-stars:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install requests  

    # Step 4: Run the Python script
    - name: Run get_total_stars.py script
      run: |
        python scripts/get_total_stars.py  
